### ISSUE TITLE
Custom Macro Inputs are Invisible

### ISSUE THREAD

**Issue by mijodong** [brh55/mymacrosnow#14]
Values input into the custom macro formulas are visible on Firefox but invisible on Chrome and Safari on Mac.

**Comment by brh55** [comment]
@mijodong Hey, thanks for letting me know. Do you know what version of chrome and safari you may be running on? 😃

**Comment by mijodong** [comment]
No problem! Safari 9.0.3 and Chrome 49.0.2623.75. 

Sick calculator by the way. Can't wait to see what you do next!

**Comment by brh55** [comment]
:+1: Resolved :]
